# Generated by Django 4.2.3 on 2023-07-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Marriot'), (2, 'Rixos'), (3, 'Sheraton'), (4, 'St Regis'), (5, 'Radison'), (6, 'Ritz')], max_length=100)),
            ],
        ),
    ]
